/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Bookrequest {
  archived?: boolean;
  authorName: string;
  coverImageUrl?: string;
  id?: number;
  isbn: string;
  shareable?: boolean;
  synopsis?: string;
  title: string;
}
