/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Bookresponse {
  archived?: boolean;
  authorName?: string;
  coverImageUrl?: string;
  createdDate?: string;
  id?: number;
  isbn?: string;
  lastModifiedDate?: string;
  ownerFullName?: string;
  ownerId?: number;
  rate?: number;
  shareable?: boolean;
  synopsis?: string;
  title?: string;
}
