/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Borrowedbookresponse {
  authorName?: string;
  id?: number;
  isbn?: string;
  rate?: number;
  returnApproved?: boolean;
  returned?: boolean;
  title?: string;
}
