/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Bookresponse } from '../models/bookresponse';
export interface PageresponseBookresponse {
  content?: Array<Bookresponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
