/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Borrowedbookresponse } from '../models/borrowedbookresponse';
export interface PageresponseBorrowedbookresponse {
  content?: Array<Borrowedbookresponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
