spring:
  datasource: <4 keys >
  jpa : <5keys >
  mail : <5keys >
  security:
    aouth2:
      resourceserver:
        jwt:
          issuer-uri:" http://localhost:4200"
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1/