/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { Bookrequest } from './models/bookrequest';
export type { Bookresponse } from './models/bookresponse';
export type { Borrowedbookresponse } from './models/borrowedbookresponse';
export type { FeedbackRequest } from './models/feedback-request';
export type { FeedbackResponse } from './models/feedback-response';
export type { PageresponseBookresponse } from './models/pageresponse-bookresponse';
export type { PageresponseBorrowedbookresponse } from './models/pageresponse-borrowedbookresponse';
export type { PageresponseFeedbackResponse } from './models/pageresponse-feedback-response';
export type { RegistrationRequest } from './models/registration-request';
